added static data to myaccount page and footer
linustribe/custom-url-generator-client pull request #9
Opened 2022-01-22 08:17 UTC by vtejaswini01

<img width="955" alt="Screenshot 2022-01-22 133608" src="https://user-images.githubusercontent.com/76904113/150630641-88d3c59a-037a-4cc1-8d05-c8dd11e06e36.png">

2022-01-22 10:25 UTC, khssupriya requested changes

2022-01-22 10:25 UTC, khssupriya commented on src/app/components/utils/footer/footer.component.html
> +    <!--Footer Elements -->
Comment is not necessary here

2022-01-22 10:25 UTC, khssupriya commented on src/app/components/utils/footer/footer.component.html
> +<div class="text-center" id="main">
change id from "main" to "footer"

2022-01-22 10:25 UTC, khssupriya commented on src/app/components/utils/footer/footer.component.scss
> +h5,i{
Can we have some padding to all icons?

2022-01-22 10:25 UTC, khssupriya commented on src/app/components/utils/footer/footer.component.html
> +             <a href="#" class="text-dark"><i class="fab fa-facebook"></i></a>
Let's have GitHub, yoututbe, instagram, linkedin in this order. What do you think?

2022-01-22 10:25 UTC, khssupriya commented on src/app/components/views/my-account/my-account.component.scss
> +    color:#12226b;
Use the colors in the global scss

2022-01-22 10:37 UTC, vtejaswini01 commented on src/app/components/utils/footer/footer.component.scss
> +h5,i{
The footer I pushed is not final.
I just put it to add some data to the footer
I might change the whole structure after myaccount page is done.
Besides, I will make the changes you have mentioned to the final one.

2022-01-22 10:37 UTC, vtejaswini01 commented on src/app/components/utils/footer/footer.component.html
> +             <a href="#" class="text-dark"><i class="fab fa-facebook"></i></a>
Yeah, okay

2022-01-22 10:38 UTC, vtejaswini01 commented on src/app/components/views/my-account/my-account.component.scss
> +    color:#12226b;
ok

2022-01-25 07:00 UTC, khssupriya commented
Continued in #14

2022-01-25 07:00 UTC, closed without merging